### ISSUE TITLE
Graphical bugs 1.20.1

### ISSUE THREAD

**Issue by Pscx1** [domanhthang2110/efbowtweak#1]
Graphical bugs like on those :
- https://imgur.com/a/RHJyZkA
- https://imgur.com/a/b3h5eKs

happens when using efbowtweak

It's of course with shaders only
I am using 1.20.1 with forge 47.3.12
Addidional mods: 
- oculus 1.7.0
- xenon 0.3.31

And tested on BSL and Bliss shaders

**Comment by domanhthang2110** [comment]
I haven't been able to replicate this bug but I think I know why
An updated should be out now on Curseforge, try it and update here if the problem persists
Thank you for reporting this issue

**Comment by Pscx1** [comment]
New update fixed that, thanks.
